#============================================================================================================
#                                   PLUGIN Id DE GHOSTSUSHI | CONFIG
#============================================================================================================
                               ## -------- [ AUTRES ] ------------
permission-command: "id.use"